// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddButtonController from "./add_button_controller"
application.register("add-button", AddButtonController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import LabelController from "./label_controller"
application.register("hello", LabelController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchDrugsController from "./search_drugs_controller"
application.register("search-drugs", SearchDrugsController)
